server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: enterprise-system
  datasource:
    url: jdbc:mysql://localhost:3306/hxjl?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123abc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: always
      platform: mysql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

# JWT配置
jwt:
  secret: hxjl-enterprise-system-secret-key-2024
  expiration: 1800 # 30分钟
  header: Authorization

# 日志配置
logging:
  level:
    com.hxjl: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 跨域配置
cors:
  allowed-origins: http://localhost:3000,http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true